spring:
  datasource:
    url: jdbc:mysql://8.138.3.220:3306/java_develop_demos?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: lx
    password: Liuxing031221+

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.example.repository.entry